### PR TITLE
Slider reference design

### PR DESCRIPTION
**Pull request by ducky64**
Adds the reference design for the slider module in KiCad, along with some documentation about how the design and footprints were built.
This is largely unchanged from the internal v1.1 reviews. The two READMEs are new, see [the footprint README](https://github.com/microsoft/jacdac-ddk/blob/kicad-reference/design/examples/kicad-footprints/README.md) and [board README](https://github.com/microsoft/jacdac-ddk/blob/kicad-reference/design/examples/kicad-slider/README.md), and include how we generated fabrication data for JLC as well as mounting hole silk footprints from SVGs (that aren't included, though maybe we should make them available as part of the DDK?).

~The actual hardware is still untested, though the schematic-equivalent version 1.0 worked fine.~

The fabricated hardware has now been physically tested to work.

TODOs
- [x] Rename to JD-PEC-02 and verify
- [x] Update readme to indicate that LCSC Part # was part of an old JLCPCB sample BoM, now it's JLCPCB Part #

### CODE REVIEW

**Comment by jamesadevine** [comment]
exmaples -> examples

**Comment by ducky64** [comment]
oops, fixed now. 🍁

**Comment by jamesadevine** [comment]
Looks good! Do we need to add an explicit license in the examples folder? Are we happy with Creative Commons 4.0?

**Comment by ducky64** [comment]
Disclaimer: I'm not a lawyer, this is not legal advice.

The current CC license we have on the main repo seems to be CC 4.0 Attribution. Two potential issues:
- Do we want to require attribution for what is supposed to be a reference design that others could directly build on in making their products?
- Because CC does not distinguish between documentation (analogous to source code, like schematics) and products, if we keep Attribution, what is the scope of our intent (and does the text reflect our intent)? For reference, CERN and TAPR OHL (strong copyleft) both make the distinction explicit, as does [Solderpad](http://solderpad.org/licenses/SHL-2.1/) (permissive, Apache 2.0 based - in fact it is Apache 2.0 with expanded definitions for hardware). Note that [CC does not recommend their licenses for computer hardware](https://creativecommons.org/faq/#what-are-creative-commons-licenses) and [software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) with this being one of the reasons.

**Comment by jamesadevine** [comment]
Does the design pass JLCPCB DRC?

**Comment by ducky64** [comment]
It should be - the board was designed to pretty loose design rules that are within JLC's listed capabilities, and while I don't remember if JLC had automated DRC as part of their ordering process, I didn't get any communications from them about bad design files (aside from a confirmation for tooling holes placement for assembly).

**Comment by ducky64** [comment]
Both fixes done:
- Changed references from JD-PEC-01 to JD-PEC-02 (except in the 1.1 BoM files that were sent to the board house - I consider those files frozen). Checked the JD-PEC-01 and JD-PEC-02 drawings to verify dimensions are consistent.
- Added explanation that `LCSC Part #` was from an older sample BoM in the readme

**Pull request merged**
